### ISSUE TITLE
[FR] Add documentation explaining SJ1 solder bridge

### ISSUE THREAD

**Issue by pyr0ball** [pyr0ball/pyr0piezo#41]
**Is your feature request related to a problem? Please describe.**
Currently SJ1 is only needed for instances when the end-user is supplying <6vDC to the EasyPiezi board.

**Describe the solution you'd like**
 Documentation about what it's for, why and when to use it, and how to use it should be added to the documentation site

**Additional context**
Originally suggested by maxcom

**Comment by maxcom** [comment]
I have no idea why you mentioned me here.

**Comment by pyr0ball** [comment]
@maxcom My apologies, you have the same username as one of my beta testers under a different platform. I just realized this and removed the links

**Comment by pyr0ball** [comment]
Completed in c2c6e6e
