### ISSUE TITLE
[FR]5v and 3.3v option using LM317

### ISSUE THREAD

**Issue by Afteraffekt** [pyr0ball/pyr0piezo#67]
LM317 should only take an extra pin. Check to see if it can be fit into the existing footprint.

**Comment by pyr0ball** [comment]
Using a combination of 3x resistors with an LM317, voltage adjustment can be made by switching a pin on the MCU from INPUT (high impedance) to OUTPUT-LOW, on the R2 side of the voltage divider used to set the regulator's output.

Will do research on parts cost
