### ISSUE TITLE
PP_VERSION not defined

### ISSUE THREAD

**Issue by stmcculloch** [pyr0ball/pyr0piezo#73]
Firmware only compiles in the arduino IDE when I add: 

`#define` PP_VERSION 230`

at the top of
"Pyr0_Piezo_Sensor_v2.x.x.cpp"
and
"pP_i2C.cpp"

**Comment by pyr0ball** [comment]
This tends to happen when compiling using Arduino IDE or other methods than PlatformIO, or if the user doesn't have python installed and available via the system PATH

There should be an `#ifndef` field to handle this cleanly

**Comment by pyr0ball** [comment]
Fixed in 4c7ab3e
