### ISSUE TITLE
-f upload flag in platformio.ini [BUG]

### ISSUE THREAD

**Issue by stmcculloch** [pyr0ball/pyr0piezo#76]
In line 43 of platformio.ini: 

`-fmax_errors=5`

is not understood by avrdude.

There doesn't seem to be a -f flag in the avrdude docs: https://www.nongnu.org/avrdude/user-manual/avrdude_4.html

![image](https://user-images.githubusercontent.com/9290784/85621803-b0cf4500-b61a-11ea-9303-57d5a1f5b340.png)

**Comment by pyr0ball** [comment]
Looks like we left in a gcc flag in that environment table. Just needs to be removed. I'll take care of it shortly
