### ISSUE TITLE
[MOUNT]

### ISSUE THREAD

**Issue by Tinchus2009** [pyr0ball/pyr0piezo#84]
**Is your printer similar to any that currently already have support?**
Please list any similar printers that already have Piezo mounts

Not that I know. My printer is a coreXY style, there is no info on the website, the page belonging to it it is empty

**What mounting scheme do you plan to use?**
Choose between: On-Printhead, Under-Bed, Gantry-Mount, or Other [if Other, please describe]

still not decided

**Any existing mounts with public links?**
Create a bullet-point list of any links to mounts similar to what you need, for example, from Thingiverse, TinkerCAD, GrabCAD, etc.

No

**Describe alternatives you've considered**

**Additional context**

What I need to know in order to haelp me decide installation is to know this extra information: my printer has an enclosed heated chamber, it can reach upto 200 degrees celsius, can the piezo ant its mounting stand this temperature?

**Comment by pyr0ball** [comment]
If you just want some ideas of how to implement on your printer, have a look at the Railcore integration: https://docs.pyroballpcbs.com/mounts/core-xy/railcore-ii/

Re: Heated chamber - Likely you'll start experiencing reduced sensitivity around 80°C, which generally can be compensated for using configuration. Above that, you'll need to enhance the piezo elements somewhat, either by increasing the size of the elements used, or by providing some insulation, or building your enclosure such that the mechanical force of the nozzle touch is translated outside the heated area. Using a standard piezo disk in a 200°C chamber will likely result in serious signal suppression.

That's a problem that may be able to be overcome, however. While signal from the piezo elements would be suppressed, they would not be totally eliminated. I would need to change a couple of resistors on the sensor, but I believe I could modify the circuit to handle a much higher gain input for this scenario.

Anyhoo, if you'd like to explore options for a custom board or circuit, please feel free to reach out direct on Discord or support@pyroballpcbs.com
